version: 2
jobs:
    build:
        branches:
            only:
                - master
        docker:
            - image: circleci/node:10-stretch
        steps:
            - checkout
            - deploy:
                name: Deploy
                command: |
                    cd docs/
                    git config --global user.email "cs5129606@gmail.com"
                    git config --global user.name "shijiezhou1"
                    git init
                    git add -A
                    git commit -m 'deploy [ci skip]'
                    git push -f git@github.com:shijiezhou1/vue-vuepress.git master:gh-pages



